### ISSUE TITLE
dialog.alert ignorance on double call 

### ISSUE THREAD

**Issue by EastskyKang** [ax5ui/ax5ui-kernel#11]
```js
dialog.alert([...] , function() {
	dialog.alert([...] , [...]);
});
```
위와 같이 dialog.alert 의 callback에서 다시 한번 dialog.alert 이 호출되면 두번째 alert 은 무시됩니다. 

As a snippet above, when dialog.alert is called in a callback function of another dialog.alert, it does not work.

**Comment by thomasJang** [comment]
fixed this issue
