### ISSUE TITLE
bower 일괄 업데이트가 있나요?

### ISSUE THREAD

**Issue by groovedk** [ax5ui/ax5ui-kernel#27]
커널 밑에 각각 모듈의 보워컴포넌트를 한번에 설치하거나 업데이트 할 수 있는 그런게 있나요?
각각 디렉토리에서 전부 해야하는지 뭔가 다른 설정이 가능할지 문의합니다.

**Comment by thomasJang** [comment]
쉘스크립트를 짜야 가능합니다. 헌데 윈도우라서.. 잘 될지..
