### ISSUE TITLE
mistype words In ax5.util.String

### ISSUE THREAD

**Issue by derren-korean** [ax5ui/ax5ui-kernel#31]
[http://ax5.io/ax5core/util/ax5-util.html#doc-ax5-util-left-16](url)

내용 : final이 finall로 적힘 (l이 중복되어 적혀있음.) - 단순 오타

해당 내용을 볼드, 이텔릭으로 표시하였습니다.

Return string from first index to **_finall_** index of original data.

Argument 01 : Original Data.
Argument 02 : **_finall_** index || **_finall_** character.
Usage : ax5.util.left(Argument01, Argument02)
Output

**Comment by thomasJang** [comment]
👍
