### ISSUE TITLE
ax5.util.left function 이슈 사용성 혼동 & 원래 이런 사용법인가요?

### ISSUE THREAD

**Issue by derren-korean** [ax5ui/ax5ui-kernel#33]
원인 : 해당 str에 찾고자 하는 문자가 없을때 문자열 전체를 반환하기 때문에 발생한 이슈 입니다.

원인 코드 : ax5.core.js 의 1038Line
if (isString(pos)) {
                return (str.indexOf(pos) > -1) ? str.substr(0, str.indexOf(pos)) : str;
            }

재현 방법 : 
var testString = "abcd3efd";

입력값 -> 출력값
ax5.util.left('testString',3); -> 'abc' ==== expectable
ax5.util.left('testString,' "3"); -> 'abcd' ==== expectable
ax5.util.left('testString,' "4"); -> 'abcd3efd' ==== X

질의 : 대상 str에 반환값이 없으면 "" 을 반환해야 할 것 같습니다.
재현 방법에서 나온 것처럼, 문자열이 없는 것이라면 없다고 반환해주어야 합니다.
그렇지 않을 경우, 사용자에겐 해당 문자열이 있기때문에 left되었다고 판단하기 때문입니다.

**Comment by thomasJang** [comment]
말씀대로 코어를 수정했습니다. 감사합니다. 👍

**Comment by derren-korean** [comment]
{
          args: [ 'abc4', '4' ],
          expect: 'abc',
          explanation: 'abc4, "4"'
      },
      {
          args: [ 'abc', '4' ],
          expect: 'abc',
          explanation: 'abc, "4"'
      }

기존 두 결과값이 같아서 혼동될꺼라 판단했었습니다. 위설명은 조금 난해했습니다.
