### ISSUE TITLE
ax5.util.getType(null) 이 undefined를 반환합니다.

### ISSUE THREAD

**Issue by hyunjun19** [ax5ui/ax5ui-kernel#50]
<img width="747" alt="2016-09-28 9 43 21" src="https://cloud.githubusercontent.com/assets/421863/18913818/f92ab90e-85c4-11e6-8ee7-5e5b883e999c.png">

제 생각에는 `undefined`는 변수나 프러퍼티가 선언된적이 없음을 의미하고 `null`은 값이 존재하지 않음을 의미하기 때문에 두 가지를 구분해서 처리해 주어야 한다고 생각합니다.

따라서 ax5.util.getType(null)은 `"null"`을 반환하는게 더 명확할 것 같습니다.

**Comment by thomasJang** [comment]
null 은 'null'이 되도록 수정했습니다.

**Comment by hyunjun19** [comment]
https://github.com/ax5ui/ax5ui-kernel/pull/56/commits/fb95003704941e7ab94693c086a285e1091ba01e ax5.util.getType(undefined) 결과 값도 'null'이 나오는 버그 수정

**Comment by hyunjun19** [comment]
테스트 이제 통과~
