### ISSUE TITLE
ax5.util.isNodelist() 메서드의 반환값이 boolean이 아닌 경우가 있습니다.

### ISSUE THREAD

**Issue by hyunjun19** [ax5ui/ax5ui-kernel#51]
ax5.util.isNodelist() 메서드의 반환값이 boolean이 아닌 경우가 있습니다.
`undefined`가 아니라 `false`가 반환되어야 할 것 같습니다.

<img width="757" alt="2016-09-28 9 49 50" src="https://cloud.githubusercontent.com/assets/421863/18913905/9aba1166-85c5-11e6-9b60-98a1638cb016.png">

**Comment by thomasJang** [comment]
false 가 나오도록 변경했습니다.

**Comment by hyunjun19** [comment]
테스트 모두 통과~
