### ISSUE TITLE
ax5.util.isDateFormat() input 값이 "201601011200" 처럼 예상보다 길게 들어오는 경우

### ISSUE THREAD

**Issue by hyunjun19** [ax5ui/ax5ui-kernel#52]
아래 같은 경우 `true`, `false`는 @thomasJang 이 정하면 될꺼 같아요.
정하시면 테스트 코드도 수정하겠습니다.

```js
ax5.util.isDateFormat("201601011200")
ax5.util.isDateFormat("2016-01-01T12:00+09:00")
```

<img width="693" alt="2016-09-28 9 55 24" src="https://cloud.githubusercontent.com/assets/421863/18914081/869a0712-85c6-11e6-9695-b154e3ae94e9.png">

**Comment by thomasJang** [comment]
둘 다 true로 가겠습니다.
```
ax5.util.isDateFormat("1981-02-22T09:00:00+09:00")
ax5.util.isDateFormat("2016-01-01T12:00+09:00") 
```
를 받을 수 있도록 core를 수정하였습니다.

그런데 그렇게 수정하니
`ax5.util.isDateFormat("2016-01-011aaaa")`
이런것도 true로 처리 되네요. 하지만 new Date함수가 처리 해주니 군말없이 true로 해야 겠습니다.

**Comment by hyunjun19** [comment]
test all green~!
