### ISSUE TITLE
Item on Click

### ISSUE THREAD

**Issue by creaturerigger** [ax5ui/ax5ui-kernel#6]
I am trying to find how to create item on click function out but i could not what am i missing? Can you please give an example how to do it? I tried something like this:

```js
menu.onLoad = function(){ $(this).find("[data-menu-item-index]").on('click', function(){
 var index = $(this).getAttribute("data-menu-item-index");
 if(index == 0){ do something.... } 
else if(index == 1){ do another thing } 
else if(index ==2){ do etc... } }); };
```

**Comment by thomasJang** [comment]
Check this sample
http://codepen.io/thomasJang/pen/yJLQKr

**Comment by creaturerigger** [comment]
Thank You @brant-hwang and @thomasJang. I did this and its working

`con_menu.onLoad = function () {        
        $('div.ax5-ui-menu').find('.ax-menu-item, .ax-menu-item-html').bind('click', function () {
            var index = $(this).attr('data-menu-item-index');
            switch(index){
                case "0":
                    do something;
                    break;
                case "1":
                    do another thing;
                    break;
                case "2":
                    do something else;
                    break;                
                default:
                    break;
            }
        });`

 but it must have a better way like every item can have an id attribute to assign a function according to the id like:

`var menu = new ax5.ui.menu({
    position: "absolute",
    items: [
               {
                icon: '<span class="fa fa-user"></span>',
                label: 'New User',
                id: 'item_newuser'
               }
               ]
});`

**Comment by brant-hwang** [comment]
i don't know what you say.
now i updated CodePen Code. http://codepen.io/anon/pen/yJLGNL
i can find menu.onClick function.
you can access id from function argument(this), so you can switch this.id.

if you have more questions. just comment here.

thank you.

**Comment by thomasJang** [comment]
`argument(this) === menu.items.item`

**Comment by creaturerigger** [comment]
Thank you @brant-hwang but unfortunately there wasn't any information about this in the documentation i got it now.

**Comment by thomasJang** [comment]
:+1:
