### ISSUE TITLE
`dialog.close()` 메서드 호출시 콜백이 호출되지 않습니다.

### ISSUE THREAD

**Issue by hyunjun19** [ax5ui/ax5ui-kernel#83]
```js
    it('Basic Alert expect open, close', function(done){
        dialog.alert('Alert message', function(){
            checkClose(dialog, 'dialog close fail.', done);
        });

        // open check
        dialog.activeDialog.attr('data-ax5-ui').should.equal('dialog', 'dialog open fail.');
        dialog.close();
    });
```

위 코드에서 `dialog.close();` 메서드가 호출되면 `dialog.alert`에서 정의한 callback이 호출되지 않습니다.
이건 의도된 상황인가요?

전체 코드는 [여기](https://github.com/hyunjun19/ax5ui-kernel/blob/master/src/ax5ui-dialog/test/test.dialog.js#L27)를 참고해 주세요.

**Comment by thomasJang** [comment]
의도된 상황일리가요.. 고려하지 못한 상황이네요. 감사합니다. 수정했습니다.

**Comment by hyunjun19** [comment]
테스트 성공했네요... ;)

**Comment by thomasJang** [comment]
:+1:  전 그로기 상태

**Comment by hyunjun19** [comment]
@thomasJang https://www.youtube.com/watch?v=c7rCyll5AeY cheer up~!
