### ISSUE TITLE
test.picker html 파일에서 css 적용이 안 되는 문제 때문에 문의 드립니다. 

### ISSUE THREAD

**Issue by kimtaeok** [ax5ui/ax5ui-kernel#92]
아래와 같이 빨간색 부분에 CSS가 적용 되지 않아 어떻게 해야할지 문의드립니다.
![default](https://cloud.githubusercontent.com/assets/18026051/21676687/1140c166-d37a-11e6-9cff-625d2a50efff.jpg)

**Comment by thomasJang** [comment]
test.picker.html 파일은 테스트 코드용 이기 때문에 CSS를 head에 안넣어두어서 그렇습니다.
test.*.html, test.*.js 파일은 신경 안쓰셔도 될것 같아요. 사람을 위한 코드가 아니에요
