### ISSUE TITLE
axboot 설치후  method  undefined for the type 에러 메시지가 나오는 문제 때문에 문의드립니다.

### ISSUE THREAD

**Issue by kimtaeok** [ax5ui/ax5ui-kernel#93]
첨부한 아래 사진처럼  undefined type 에러가 뜨는데 혹시 빠진 부분이 있을까요?
![default](https://cloud.githubusercontent.com/assets/18026051/21708008/cbb815c4-d417-11e6-8bf3-73d176ab91cb.jpg)

**Comment by thomasJang** [comment]
아네 위 이슈제기는 https://github.com/axboot/ax-boot-framework 여기에 하셔야 됩니다. 여기는 ax5ui 입니다. 수고하세요
